### ISSUE TITLE
Name git2-ext instead

### ISSUE THREAD

**Issue by arxanas** [gitext-rs/git2-ext#3]
This is kind of silly, but maybe we should call it git2-ext? Otherwise it looks like it's a library which is responsible for somehow converting "git" to "ext", like [`dos2unix`](https://linux.die.net/man/1/dos2unix) or [`nl2br`](https://www.php.net/manual/en/function.nl2br.php) 😅

**Comment by epage** [comment]
Sure!

**Comment by epage** [comment]
Done
